# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
#   Ensure PostgreSQL is added to system PATH
#    $ export PATH=$PATH:/usr/local/bin
#
# Configure Using Gemfile
# gem 'pg'
#
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Settings.PostgreSQL.username %>
  password: <%= Settings.PostgreSQL.password %>
  host: <%= Settings.PostgreSQL.host %>

development:
  database: SknServices_development
  <<: *defaults

test:
  database: SknServices_test
  <<: *defaults

production:
  database: SknServices_production
  <<: *defaults

